first_names = [
    'James', 'Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Isabella', 'Sophia', 'Lucas', 'Mia',
    'Jackson', 'Leah', 'Aiden', 'Elijah', 'Harper', 'Caden', 'Amelia', 'Abigail', 'Benjamin', 'Ethan',
    'Mason', 'Ella', 'Alexander', 'Scarlett', 'Aria', 'Grayson', 'Luna', 'Carter', 'Chloe', 'Sofia',
    'Henry', 'Avery', 'Samuel', 'Ellie', 'Max', 'Grace', 'Jack', 'Madison', 'Lily', 'Zoe',
    'Lillian', 'Nora', 'Sebastian', 'Riley', 'Leo', 'Hazel', 'Lucy', 'Mila', 'Layla', 'Zoey',
    'Camila', 'Mateo', 'Liam', 'Nathan', 'Logan', 'Jayden', 'Elizabeth', 'Owen', 'Addison', 'Isaac',
    'Natalie', 'Landon', 'Bella', 'Evelyn', 'Aubrey', 'Caleb', 'Hudson', 'Emily', 'Penelope', 'Scarlet',
    'Eli', 'Victoria', 'Madelyn', 'Nova', 'Emilia', 'Joseph', 'Ryder', 'Madeline', 'Kimberly', 'Levi',
    'Mila', 'Easton', 'Peyton', 'Grace', 'Kai', 'Autumn', 'Gabriel', 'Brielle', 'Faith', 'Nevaeh',
    'George', 'John', 'Thomas', 'James', 'James', 'John', 'Andrew', 'Martin', 'William', 'John',
    'James', 'Zachary', 'Millard', 'Franklin', 'James', 'Abraham', 'Andrew', 'Ulysses', 'Rutherford', 'James',
    'Chester', 'Grover', 'Benjamin', 'Grover', 'William', 'Theodore', 'William', 'Woodrow', 'Warren', 'Calvin',
    'Herbert', 'Franklin', 'Harry', 'Dwight', 'John', 'Lyndon', 'Richard', 'Gerald', 'Jimmy', 'Ronald',
    'George', 'Bill', 'George', 'Barack', 'Joe','Martha', 'Abigail', 'Martha', 'Dolley', 'Elizabeth', 'Louisa', 'Emily', 'Sarah', 'Angelica',
    'Anna', 'Letitia', 'Julia', 'Sarah', 'Margaret', 'Abigail', 'Jane', 'Mary', 'Eliza', 'Grace',
    'Frances', 'Caroline', 'Jane', 'Harriet', 'Julia', 'Lucy', 'Edith', 'Ellen', 'Helen', 'Lou',
    'Grace', 'Florence', 'Edith', 'Nellie', 'Ellen', 'Lou', 'Grace', 'Florence', 'Edith', 'Nellie',
    'Edith', 'Grace', 'Lou', 'Helen', 'Edith', 'Grace', 'Bess', 'Mamie', 'Florence', 'Lou',
    'Elizabeth', 'Rosalynn', 'Nancy', 'Barbara', 'Hillary', 'Laura', 'Michelle', 'Jill'
]

last_names = [
    'Crabtree', 'Lobsterman', 'Shrimpton', 'Clamsworth', 'Oysterson', 'Barnacleton', 'Musselman', 'Scallopton', 'Krabby', 'Bassington',
    'Clamford', 'Lobsterson', 'Prawlington', 'Snailsworth', 'Whaleton', 'Shellington', 'Oysterville', 'Barnacleton', 'Crabbington', 'Krillington',
    'Whalesworth', 'Snailman', 'Crawdadsworth', 'Squidwardson', 'Starfishman', 'Whelkington', 'Squidworthy', 'Barnacleman', 'Shellsworth', 'Lobsterville',
    'Krabbington', 'Snailton', 'Musselsworth', 'Whaleman', 'Starfishworth', 'Clamworthy', 'Squidsworth', 'Krabbsworth', 'Shrimpsworth', 'Whelkman',
    'Lobsterworth', 'Clamford', 'Barnacleson', 'Shrimpworthy', 'Shellsworth', 'Prawnsworth', 'Oysterborough', 'Squidworth', 'Krillworthy', 'Starfishborough',
    'Whaleson', 'Crawdadborough', 'Bassington', 'Musselworth', 'Lobstertown', 'Snailworthy', 'Clamsville', 'Oysterville', 'Barnacleburg', 'Shrimptown',
    'Krillton', 'Clamsville', 'Whalesburg', 'Bassborough', 'Lobsterburg', 'Shelltown', 'Oysterville', 'Shrimpsburg', 'Snailton', 'Musselburg',
    'Barnacleton', 'Clamsville', 'Oysterburg', 'Krilltown', 'Whalesburg', 'Shelltown', 'Lobsterburg', 'Shrimpsburg', 'Bassington', 'Musselsburg',
    'Oysterville', 'Barnacleton', 'Clamsville', 'Snailton', 'Shrimpsburg', 'Krilltown', 'Musselburg', 'Lobsterburg', 'Bassington', 'Whalesburg', 'Brook', 'Lake', 'Rivers', 'Wells', 'Pond', 'Marsh', 'Bay', 'Shore', 'Cove', 'Delta',
    'Harbor', 'Tides', 'Stream', 'Quay', 'Bayou', 'Ocean', 'Gulf', 'Seaway', 'Lagoon', 'Estuary',
    'Basin', 'Fjord', 'Strait', 'Rapids', 'Channel', 'Canal', 'Sound', 'Falls', 'Cascade', 'Inlet',
    'Reef', 'Beach', 'Loch', 'Vale', 'Harbor', 'Dunes', 'Shoal', 'Bight', 'Brook', 'Mere', 'Cove',
    'Ford', 'Isle', 'Knoll', 'Reach', 'Pools', 'Shoals', 'Summit', 'Springs', 'Ridge', 'Mound',
    'Crest', 'Terrace', 'Glen', 'Stream', 'Wave', 'Pines', 'Banks', 'Slope', 'Crest', 'Rise',
    'Isles', 'Head', 'Ridge', 'Shoals', 'Slope', 'Rise', 'Isles', 'Head', 'Knoll', 'Crest',
    'Banks', 'Pines', 'Wave', 'Stream', 'Glen', 'Terrace', 'Crest', 'Mound', 'Ridge', 'Springs',
    'Summit', 'Shoals', 'Pools', 'Reach', 'Knoll', 'Isle', 'Ford', 'Cove', 'Mere', 'Brook',
    'Bight', 'Shoal', 'Dunes', 'Beach', 'Reef', 'Inlet', 'Cascade', 'Falls', 'Sound',
    'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Syrah', 'Zinfandel', 'Malbec', 'Chardonnay',
    'Sauvignon Blanc', 'Riesling', 'Pinot Grigio', 'Gewürztraminer', 'Viognier', 'Chenin Blanc',
    'Tempranillo', 'Sangiovese', 'Nebbiolo', 'Barbera', 'Gamay', 'Carmenere', 'Petit Verdot',
    'Petite Sirah', 'Grüner Veltliner', 'Moscato', 'Prosecco', 'Champagne', 'Cabernet Franc',
    'Muscat', 'Shiraz', 'Grenache', 'Verdejo', 'Albariño', 'Semillon', 'Roussanne', 'Marsanne',
    'Viura', 'Corvina', 'Rondinella', 'Molinara', 'Negroamaro', 'Primitivo', 'Aglianico', 'Fiano',
    'Vermentino', 'Aligoté', 'Cinsault', 'Carignan', 'Glera', 'Tannat', 'Montepulciano', 'Cannonau'   
]

nick_names = [
    'Dune','1984', 'Brave New World','Sapiens','Outliers','Inferno','Misery','Jurassic Park',
    'Fahrenheit 451',
    'Frankenstein',
    'Odyssey',
    'Ulysses',
    'Dracula',
    'Moby-Dick',
    'Odyssey',
    'Ishmael',
    "Gulliver's Travels",
    'Metamorphosis',
    'Othello',
    'Macbeth',
    'Big Show',
    'Avid Reader',
    'The Closer',
    'Bank Teller',
    'Guard Dog',
    'Service Dog',
    'Therapy Dog',
    'Herding Dog',
    'Search Dog',
    'Rescue Dog',
    'Police Dog',
    'Guide Dog',
    'Sniffer Dog',
    'Companion Dog',
    'Show Dog',
    'Hunting Dog',
    'Sled Dog',
    'Assistance Dog',
    'Detection Dog',
    'Tracker Dog',
    'Farm Dog',
    'Pet Dog',
    'Sentry Dog',
    'War Dog'
]

