first_names = [
    'James', 'Ankit', 'Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Isabella', 'Sophia', 'Lucas', 'Mia',
    'Jackson', 'Leah', 'Aiden', 'Elijah', 'Harper', 'Caden', 'Amelia', 'Abigail', 'Benjamin', 'Ethan',
    'Mason', 'Ella', 'Alexander', 'Scarlett', 'Aria', 'Grayson', 'Luna', 'Carter', 'Chloe', 'Sofia',
    'Henry', 'Avery', 'Samuel', 'Ellie', 'Max', 'Grace', 'Jack', 'Madison', 'Lily', 'Zoe',
    'Lillian', 'Nora', 'Sebastian', 'Riley', 'Leo', 'Hazel', 'Lucy', 'Mila', 'Layla', 'Zoey',
    'Camila', 'Mateo', 'Liam', 'Nathan', 'Logan', 'Jayden', 'Elizabeth', 'Owen', 'Addison', 'Isaac',
    'Natalie', 'Landon', 'Bella', 'Evelyn', 'Aubrey', 'Caleb', 'Hudson', 'Emily', 'Penelope', 'Scarlet',
    'Eli', 'Victoria', 'Madelyn', 'Nova', 'Emilia', 'Joseph', 'Ryder', 'Madeline', 'Kimberly', 'Levi',
    'Mila', 'Easton', 'Peyton', 'Grace', 'Kai', 'Autumn', 'Gabriel', 'Brielle', 'Faith', 'Nevaeh',
    'George', 'John', 'Thomas', 'James', 'James', 'John', 'Andrew', 'Martin', 'William', 'John',
    'James', 'Zachary', 'Millard', 'Franklin', 'James', 'Abraham', 'Andrew', 'Ulysses', 'Rutherford', 'James',
    'Chester', 'Grover', 'Benjamin', 'Grover', 'William', 'Theodore', 'William', 'Woodrow', 'Warren', 'Calvin',
    'Herbert', 'Franklin', 'Harry', 'Dwight', 'John', 'Lyndon', 'Richard', 'Gerald', 'Jimmy', 'Ronald',
    'George', 'Bill', 'George', 'Barack', 'Joe','Martha', 'Abigail', 'Martha', 'Dolley', 'Elizabeth', 'Louisa', 'Emily', 'Sarah', 'Angelica',
    'Anna', 'Letitia', 'Julia', 'Sarah', 'Margaret', 'Abigail', 'Jane', 'Mary', 'Eliza', 'Grace',
    'Frances', 'Caroline', 'Jane', 'Harriet', 'Julia', 'Lucy', 'Edith', 'Ellen', 'Helen', 'Lou',
    'Grace', 'Florence', 'Edith', 'Nellie', 'Ellen', 'Lou', 'Grace', 'Florence', 'Edith', 'Nellie',
    'Edith', 'Grace', 'Lou', 'Helen', 'Edith', 'Grace', 'Bess', 'Mamie', 'Florence', 'Lou',
    'Elizabeth', 'Rosalynn', 'Nancy', 'Barbara', 'Hillary', 'Laura', 'Michelle', 'Jill', 'AJ', 'AC', 'JJ', 'EJ', 'LJ', 'CJ', 'DJ', 'GJ', 'Akira', 'Mateo', 'Zahra', 'Ananya', 'Santiago', 'Aisha', 'Luca', 'Aarav', 'Amara', 'Nadia',
    'Yuki', 'Ravi', 'Eva', 'Omar', 'Hana', 'Makoto', 'Lila', 'Kai', 'Sofia', 'Rohan',
    'Isabella', 'Caden', 'Aaradhya', 'Aiden', 'Olivia', 'Yuna', 'Matea', 'Javier', 'Aria', 'Yusuke',
    'Liam', 'Nina', 'Yusuf', 'Maya', 'Cristiano', 'Aishwarya', 'Mila', 'Rafael', 'Ava', 'Yasmine',
    'Leon', 'Zara', 'Haruto', 'Luna', 'Rahul', 'Zain', 'Elena', 'Aditya', 'Isaac', 'Aiko',
    'Antonio', 'Sophie', 'Kenzo', 'Zainab', 'José', 'Ella', 'Mia', 'Arjun', 'Lina', 'Noah',
    'Sara', 'Akari', 'Elijah', 'Aaliyah', 'Ryota', 'Amelia', 'David', 'Leila', 'Lincoln', 'Aisha',
    'Victor', 'Sophia', 'Nina', 'Hiroshi', 'Liam', 'Riya', 'Kenta', 'Ayla', 'Kazuki', 'Jasmine',
    'Cleo', 'Tariq', 'Aanya', 'Nolan', 'Anaya', 'Luca', 'Yara', 'Adrian', 'Elina', 'Sora',
    'Emi', 'Amir', 'Zoe', 'Riko', 'Mason', 'Sophie', 'Haru', 'Amina', 'Ethan', 'Lily',
    'Mateo', 'Aiden', 'Nyla', 'Max', 'Mira', 'Sora', 'Ayman', 'Emery', 'Liam', 'Amara',
    'Zara', 'Rohan', 'Yara', 'Omar', 'Eva', 'Maya', 'Kian', 'Ariana', 'Kai', 'Isabella',
    'Jun', 'Naomi', 'Zane', 'Ava', 'Yuki', 'Zahra', 'Hudson', 'Mia', 'Leila', 'Kazuki',
    'Zainab', 'Arjun', 'Yusuf', 'Zain', 'Hana', 'Riya', 'Luca', 'Lina', 'Aria', 'Javier',
    'Liam', 'Yuna', 'Matea', 'Santiago', 'Nadia', 'Hiroshi', 'Sophia', 'Makoto', 'Lily', 'Aarav',
    'Maya', 'Zoe', 'Kenta', 'Yasmine', 'José', 'Nina', 'Ella', 'Akari', 'David', 'Elena',  'Liamuel', 'Arianae', 'Kazara', 'Aidanah', 'Sofiano', 'Emelia', 'Olivonte', 'Haruko', 'Makari', 'Rianah',
    'Isarina', 'Cadenzo', 'Arielleo', 'Leiano', 'Milaiah', 'Sophuen', 'Yukariel', 'Zainaiah', 'Harioh', 'Lianaomi',
    'Mikenzo', 'Liara', 'Hudsonna', 'Nolena', 'Santara', 'Yukuna', 'Kenzara', 'Avelena', 'Rohanah', 'Saraya', 'Liamuel', 'Arianae', 'Kazara', 'Aidanah', 'Sofiano', 'Emelia', 'Olivonte', 'Haruko', 'Makari', 'Rianah',
    'Isarina', 'Cadenzo', 'Arielleo', 'Leiano', 'Milaiah', 'Sophuen', 'Yukariel', 'Zainaiah', 'Harioh', 'Lianaomi',
    'Mikenzo', 'Liara', 'Hudsonna', 'Nolena', 'Santara', 'Yukuna', 'Kenzara', 'Avelena', 'Rohanah', 'Saraya',
    'Zarion', 'Alysandro', 'Niamara', 'Jasmina', 'Eliandro', 'Isaraya', 'Zayelle', 'Kyrian', 'Aysara', 'Elianora',
    'Rhiara', 'Olyvia', 'Jaylenzo', 'Sofari', 'Kianara', 'Lylitha', 'Naviyah', 'Mikariel', 'Jovanni', 'Elarian',
    'Yasmina', 'Kyliara', 'Johariel', 'Amadara', 'Kaelina', 'Zionna', 'Avelynne', 'Rashari', 'Mariantho', 'Saraiel',
    'Elyssia', 'Nolantho', 'Saralyn', 'Kyndara', 'Averil', 'Zyleria', 'Halyssa', 'Yovani', 'Mikaiah', 'Nyleah',
    'Zairon', 'Averina', 'Jasmineo', 'Kysondra', 'Oliviana', 'Zyanya', 'Elioana', 'Saranoah', 'Kaeliana', 'Yohannes',
    'Kaviel', 'Yariza', 'Zyviana', 'Navario', 'Aylaitha', 'Kalyssa', 'Elyasandro', 'Zarionna', 'Elariana', 'Joliana',
    'Zanderia', 'Ilyssio', 'Ryleiana', 'Lynovio', 'Kyrielle', 'Ezriano', 'Olivianne', 'Averiana', 'Zykari', 'Raeliana'
]

last_names = [
    'Crabtree', 'Lobsterman', 'Shrimpton', 'Clamsworth', 'Oysterson', 'Barnacleton', 'Musselman', 'Scallopton', 'Krabby', 'Bassington',
    'Clamford', 'Lobsterson', 'Prawlington', 'Snailsworth', 'Whaleton', 'Shellington', 'Oysterville', 'Barnacleton', 'Crabbington', 'Krillington',
    'Whalesworth', 'Snailman', 'Crawdadsworth', 'Squidwardson', 'Starfishman', 'Whelkington', 'Squidworthy', 'Barnacleman', 'Shellsworth', 'Lobsterville',
    'Krabbington', 'Snailton', 'Musselsworth', 'Whaleman', 'Starfishworth', 'Clamworthy', 'Squidsworth', 'Krabbsworth', 'Shrimpsworth', 'Whelkman',
    'Lobsterworth', 'Clamford', 'Barnacleson', 'Shrimpworthy', 'Shellsworth', 'Prawnsworth', 'Oysterborough', 'Squidworth', 'Krillworthy', 'Starfishborough',
    'Whaleson', 'Crawdadborough', 'Bassington', 'Musselworth', 'Lobstertown', 'Snailworthy', 'Clamsville', 'Oysterville', 'Barnacleburg', 'Shrimptown',
    'Krillton', 'Clamsville', 'Whalesburg', 'Bassborough', 'Lobsterburg', 'Shelltown', 'Oysterville', 'Shrimpsburg', 'Snailton', 'Musselburg',
    'Barnacleton', 'Clamsville', 'Oysterburg', 'Krilltown', 'Whalesburg', 'Shelltown', 'Lobsterburg', 'Shrimpsburg', 'Bassington', 'Musselsburg',
    'Oysterville', 'Barnacleton', 'Clamsville', 'Snailton', 'Shrimpsburg', 'Krilltown', 'Musselburg', 'Lobsterburg', 'Bassington', 'Whalesburg', 'Brook', 'Lake', 'Rivers', 'Wells', 'Pond', 'Marsh', 'Bay', 'Shore', 'Cove', 'Delta',
    'Harbor', 'Tides', 'Stream', 'Quay', 'Bayou', 'Ocean', 'Gulf', 'Seaway', 'Lagoon', 'Estuary',
    'Basin', 'Fjord', 'Strait', 'Rapids', 'Channel', 'Canal', 'Sound', 'Falls', 'Cascade', 'Inlet',
    'Reef', 'Beach', 'Loch', 'Vale', 'Harbor', 'Dunes', 'Shoal', 'Bight', 'Brook', 'Mere', 'Cove',
    'Ford', 'Isle', 'Knoll', 'Reach', 'Pools', 'Shoals', 'Summit', 'Springs', 'Ridge', 'Mound',
    'Crest', 'Terrace', 'Glen', 'Stream', 'Wave', 'Pines', 'Banks', 'Slope', 'Crest', 'Rise',
    'Isles', 'Head', 'Ridge', 'Shoals', 'Slope', 'Rise', 'Isles', 'Head', 'Knoll', 'Crest',
    'Banks', 'Pines', 'Wave', 'Stream', 'Glen', 'Terrace', 'Crest', 'Mound', 'Ridge', 'Springs',
    'Summit', 'Shoals', 'Pools', 'Reach', 'Knoll', 'Isle', 'Ford', 'Cove', 'Mere', 'Brook',
    'Bight', 'Shoal', 'Dunes', 'Beach', 'Reef', 'Inlet', 'Cascade', 'Falls', 'Sound',
    'Cabernet Sauvignon', 'Merlot', 'Pinot Noir', 'Syrah', 'Zinfandel', 'Malbec', 'Chardonnay',
    'Sauvignon Blanc', 'Riesling', 'Pinot Grigio', 'Gewürztraminer', 'Viognier', 'Chenin Blanc',
    'Tempranillo', 'Sangiovese', 'Nebbiolo', 'Barbera', 'Gamay', 'Carmenere', 'Petit Verdot',
    'Petite Sirah', 'Grüner Veltliner', 'Moscato', 'Prosecco', 'Champagne', 'Cabernet Franc',
    'Muscat', 'Shiraz', 'Grenache', 'Verdejo', 'Albariño', 'Semillon', 'Roussanne', 'Marsanne',
    'Viura', 'Corvina', 'Rondinella', 'Molinara', 'Negroamaro', 'Primitivo', 'Aglianico', 'Fiano',
    'Vermentino', 'Aligoté', 'Cinsault', 'Carignan', 'Glera', 'Tannat', 'Montepulciano', 'Cannonau','Champagne', 'Sapphire', 'Emerald', 'Opal', 'Mocha', 'Platinum', 'Pearl', 'Crimson', 'Lavender',
    'Aqua', 'Rosegold', 'Ivory', 'Mauve', 'Obsidian', 'Goldenrod', 'Sunshine', 'Breeze', 'Storm', 'Calm', 'Fog', 'Blizzard', 'Heatwave', 'Drizzle', 'Tornado', 'Hail',
    'Drought', 'Rainbow', 'Sleet', 'Mist', 'Thunder', 'Cyclone', 'Chill', 'Monsoon', 'Haze', 'Gale', 'Popović', 'Ivanović', 'Stojanović', 'Jovanović', 'Nikolić', 'Đorđević', 'Kovačević', 'Petrović', 'Marković', 'Vuković',
    'Milosavljević', 'Ristić', 'Todorović', 'Pavlović', 'Stanković', 'Janković', 'Aleksić', 'Simić', 'Dragić', 'Gajić',
    'Raković', 'Tošić', 'Nenadović', 'Milinković', 'Milićević', 'Nkosi', 'Kabongo', 'Ouedraogo', 'Sango', 'Lumumba', 'Mukendi', 'Mwamba', 'Bemba', 'Bokassa', 'Diallo',
    'Ntumba', 'Abimbola', 'Makamba', 'Mumba', 'Kagame', 'Mulumba', 'Nzuzi', 'Banza', 'Tshibanda', 'Ogbonna',
    'Onyeka', 'Mbembe', 'Ngozi', 'Kaninda', 'Ikechukwu', 'Sato', 'Suzuki', 'Takahashi', 'Tanaka', 'Watanabe', 'Ito', 'Yamamoto', 'Nakamura', 'Kobayashi', 'Kato',
    'Yoshida', 'Yamada', 'Sasaki', 'Yamaguchi', 'Matsumoto', 'Patel', 'Shah', 'Singh', 'Kumar', 'Joshi', 'Mehta', 'Gupta', 'Sharma', 'Verma', 'Reddy',
    'Chopra', 'Pandey', 'Malhotra', 'Sinha', 'Rao', 'Iyer', 'Mittal', 'Chauhan', 'Yadav', 'Bhat',  'Smith', 'Johnson', 'Williams', 'Jones', 'Brown', 'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor',
    'Anderson', 'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson', 'Garcia', 'Martinez', 'Jones',
    'Davis', 'Miller', 'Wilson', 'Moore', 'Taylor', 'Anderson', 'Thomas', 'Jackson', 'White', 'Harris',
    'Martin', 'Thompson', 'Garcia', 'Martinez', 'Robinson', 'Clark', 'Lewis', 'Lee', 'Walker', 'Hall',
    'Allen', 'Young', 'Hill', 'Wright', 'Scott', 'Adams', 'Evans', 'Ford', 'Dixon', 'Zzyzx'
]

nick_names = [
    'Dune','1984', 'Brave New World','Sapiens','Outliers','Inferno','Misery','Jurassic Park',
    'Fahrenheit 451', 'Frankenstein',
    'Odyssey',
    'Ulysses',
    'Dracula',
    'Moby-Dick',
    'Odyssey',
    'Ishmael',
    "Gulliver's Travels",
    'Metamorphosis',
    'Othello',
    'Macbeth',
    'Big Show',
    'Avid Reader',
    'The Closer',
    'Bank Teller',
    'Guard Dog',
    'Service Dog',
    'Therapy Dog',
    'Herding Dog',
    'Search Dog',
    'Rescue Dog',
    'Police Dog',
    'Guide Dog',
    'Sniffer Dog',
    'Companion Dog',
    'Show Dog',
    'Hunting Dog',
    'Sled Dog',
    'Assistance Dog',
    'Detection Dog',
    'Tracker Dog',
    'Farm Dog',
    'Pet Dog',
    'Sentry Dog',
    'War Dog'
]

locations = [
    'Atlanta',
    'Boston',
    'Brooklyn',
    'Charlotte',
    'Chicago',
    'Cleveland',
    'Dallas',
    'Denver',
    'Detroit',
    'San Francisco',
    'Houston',
    'Indianapolis',
    'Los Angeles',
    'Seattle',
    'Memphis',
    'Miami',
    'Milwaukee',
    'Minnesota',
    'New Orleans',
    'New York',
    'Oklahoma City',
    'Orlando',
    'Philadelphia',
    'Phoenix',
    'Portland',
    'Sacramento',
    'San Antonio',
    'Toronto',
    'Utah',
    'Washington'
]


team_names = [
'Beat', 'Vibe', 'Discovery', 'Yetis', 'Legacy', 'Rattlesnakes', 'Blizzards', 'Leopards','Wave', 'Pioneers',
 'Sorcery', 'Druids', 'Fighters', 'Clerics', 'Mana', 'Goblins', 'Trolls', 'Mountain Orcs', 'Dragonborns', 'Guildmasters',
 'Witchcraft', 'Crimson Plague', 'Archmages', 'Paladins', 'Duskspell', 'Morning Stars', 'Great Axes', 'Dungeon',
 'Pickles', 'First Light', 'Crunk', 'Bass', 'Squirrels', 'Scholars', 'Necromancers', 'Ornothologists'
]